My implementation of https://github.com/ircv3/ircv3-ideas/issues/108
unrealircd/unrealircd-contrib pull request #98
Opened 2023-08-24 16:14 UTC by ValwareIRC

##  `+draft/rated`
This lets users who post media mark their posts as "Not safe for work" to some degree, allowing other users to choose whether or not they want to see this post.

2023-08-27 06:38 UTC, syzop requested changes

2023-08-27 06:38 UTC, syzop commented on files/rated.c
> +	"third/rated",
Could you rename the module third/rated-tag? See the other PR. I know it's not consistently implemented in contrib nor in unrealircd but the majority does it. Maybe it is good to keep that scheme from now on. Be sure to rename it both as a file and here in the header (and in the post install line, etc.).

2023-08-27 06:38 UTC, syzop commented on files/rated.c
> +        return 0;
I know i normally should not really look at contrib code, certainly not in detail, but when viewing this on github it looks weird: the `return 0` gets indented just as much as the `return 1` due to mixed spaces vs tabs usage. I suggest to just use the double tab for the `return 0` instead of eight spaces.

2023-08-27 06:49 UTC, syzop commented
Also, are you sure you want this merged already? It builds on ideas from others and then you immediately create a tag with a different name with no feedback from those others yet, so it could easily change tag names, details, etc?
I mean, if you want, I will merge (after the module name change), as this is contrib, but... it seems a little fast? :D

2023-10-23 23:50 UTC, ValwareIRC commented
There are several ideas for this, the other ideas are more limited, mine lets people use a different language or rating system. I think this could be more advanced, but I'm leaving it like this for now until there is more client code. Indeed, you don't have to merge this right now, but it would be helpful (but not necessary) if I want need someone else to test it on their network for this to be merged. I think wait for a while :D

2024-06-26 06:59 UTC, syzop commented
Is there interest in this? Would you want to see this merged?

Yeah, I'm trying to go through old PR's :)

2025-05-09 06:48 UTC, syzop commented
After 11 months this can be closed I think.

2025-05-09 06:48 UTC, closed without merging